/* guess.cpp
 *
 * Lab #6 - Another numbers game...
 *
 * Brooke Cantwell
 *
 * 5 November 2015
 *
 * Generates a random number between -20
 * and 20 and gives the user 10 tries to
 * guess the number.
 *
 */

#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

main() {

	signed int guess, rNum;
	int guessCounter = 1;
	char answer;
	bool sameNumber;

	int generateNumber (int, int);
	bool compare (int, int);

	// Ask the user if they want to guess the number

	cout << "I have a number between -20 and 20.\nCan you guess my number? (y/n) ";
	cin >> answer;

	// If the answer is no, display a message and quit the program

	if (answer == 'N' || answer == 'n')
		cout << "Too scared?" << endl;
	else
	if (answer == 'Y' || answer == 'y') {
		while (answer == 'Y' || answer == 'y') {

			// Use the generateNumber function to generate
			// a random number between a given max and min

			rNum = generateNumber (-20, 20);

			// Ask the user to guess the random number

			cout << "Please enter your first guess: ";
			cin >> guess;

			// Compare the guessed number to the random number
			// generated by the generateNumber function

			sameNumber = compare (rNum, guess);

			// If the guessed number and rNum aren't the same then let
			// the user know if their guess was too low or too high.	

			while (sameNumber == 0) {
				if (guess > rNum)
					cout << "Too high. Please guess again: ";
				if (guess < rNum)
					cout << "Too low. Please guess again: ";

				cin >> guess;

				guessCounter++;

				if (guess == rNum)
					break;
	
			} //End while (guess != rNum)		

			// Display message according to the value of guessCounter

			if (guessCounter == 10)
				cout << "You have reached the maximum number of guesses! The correct answer was " << rNum << endl;
			if (guessCounter == 1)
				cout << "Wow! Either you are insightful or got really lucky!" << endl << endl;
			if (guessCounter > 1 && guessCounter <= 3)
				cout << "That's pretty impressive! It only took you " << guessCounter << " tries to guess the number!" << endl << endl;
			if (guessCounter > 3 && guessCounter <= 7)
				cout << "I guess " << guessCounter << " tries is pretty good." << endl <<  endl;
			if (guessCounter > 7)
				cout << guessCounter << " tries? You can do better next time!" << endl << endl;

			// Ask the user if they want to play again

			cout << "Would you like to play again? (y/n) ";
			cin >> answer;

			// Reset the value of guessCounter to 1
			
			guessCounter = 1;
		} // End while answer = yes
	} // End if answer = yes

	// If the user enters a character besides 'y' or 'n' tell them to enter a valid response.	

	else
		cout << "Please enter 'y' or 'n'." << endl;
}
